#################################################################################
# RCA_outputs generated by randomly picking up TF-target and run matlab RCA 
#		random number is the same as TF-target	
# input: TF_target (TF_binding.txt)and array data with gene list (array.txt)
#        
# output: random outputs like TF_binding.txt, and result from RCA.m
#################################################################################

#!/usr/bin/perl 

# my $dir= "C:\Documents and Settings\yanbi.NIH\Desktop\matlab\RCA";
# chdir($dir);

$array = "'12up.txt'";
$array2 = "12up.txt";
$tf_binding = "5mir_input_binding.txt";
$a = "'median'";

for ($i = 1; $i < 1001; $i++) {
	open(INPUT2, $tf_binding) || die("Could not open input2.txt\n$!");
	open(OUTPUT,">output$i.txt") || die("Could not open output.txt\n$!");
	$TF = "'output$i.txt'";
		print "$TF\n";

	while (<INPUT2>) {
		$line2= $_;
		chomp($line2);
		@line2= split (/\t/, $line2);
		$size2 = @line2 - 1;

		if ($size2 != -1) { # otherwise this is an empty line
			@a = {}; # must empty @a before use it
			open(INPUT1, $array2) || die("Could not open input1.txt\n$!");

			<INPUT1>; # skip the title row
			while (<INPUT1>) {
				$line1 = $_;
				chomp($line1);
				@line1= split (/\t/, $line1);
				push @a, $line1[1];
				} # must build @a before get random # from it

				$size1 = @a;
				@strings = {};
				print OUTPUT "$line2[0]\t";

				for (1 .. $size2) {
					print OUTPUT "$a[$id = int(rand($size1 - 1)) + 1]\t";
					# should be "int(rand($size1)) + 1" if last line of input1.txt is not empty
				}
			print OUTPUT "\n";
			close(INTUT1);
		}
	
	} # run matlab
	$cmd = 'matlab -wait -nosplash -nodesktop -r "RCA('.$array.', '.$TF.', '.$a.', 0, 1);quit;"';
	system($cmd);

}close(OUTPUT);
close(INPUT2);



